Repository NeoJumper/VacationManagementSystem, pull requests merged in 2024-08, with the labels that each got.

#2 PR테스트
  src/main/java/com/kcc/untitled/UntitledApplication.java
Labels: 🛠 Setting

#4 feat: navbar & header
  pom.xml
  src/main/java/com/kcc/vacation/VacationApplication.java
  src/main/java/com/kcc/vacation/controller/HelloController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/assets/logo.png
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/components/sidebar.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/styles.css
Labels: ✨ Feature

#6 bin file ignore
  .gitignore
Labels: 🛠 Setting

#9 프론트 프로젝트 구조
  src/main/webapp/WEB-INF/views/admin/admin-calender.jsp
  src/main/webapp/WEB-INF/views/admin/cancel-vacation.jsp
  src/main/webapp/WEB-INF/views/admin/employee-management.jsp
  src/main/webapp/WEB-INF/views/admin/grant-vacation-management.jsp
  src/main/webapp/WEB-INF/views/admin/organizational-management.jsp
  src/main/webapp/WEB-INF/views/admin/request-vacation.jsp
  src/main/webapp/WEB-INF/views/admin/vacation-type-management.jsp
  src/main/webapp/WEB-INF/views/auth/login.jsp
  src/main/webapp/WEB-INF/views/auth/signIn.jsp
  src/main/webapp/WEB-INF/views/client/certification-detail.jsp
  src/main/webapp/WEB-INF/views/client/certification-list.jsp
  src/main/webapp/WEB-INF/views/client/certification-pdf.jsp
  src/main/webapp/WEB-INF/views/client/client-calender.jsp
  src/main/webapp/WEB-INF/views/client/my-page.jsp
  src/main/webapp/WEB-INF/views/client/request-vacation.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/resources/components/admin/addReasonVacationModal.jsp
  src/main/webapp/resources/components/admin/addVacationTypeModal.jsp
  src/main/webapp/resources/components/admin/showNewVacationModal.jsp
Labels: 🛠 Setting

#13 Setting/#12 utf8
  src/main/java/com/kcc/vacation/controller/HelloController.java
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/components/sidebar.jsp
Labels: 🛠 Setting

#15 사이드바에 따른 공통 패딩 설정
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/resources/components/sidebar.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/styles.css
Labels: ♻️ Refactor

#19 Feature/#11 request my vacation
  src/main/java/com/kcc/vacation/controller/HelloController.java
  src/main/webapp/WEB-INF/views/client/request-vacation.jsp
Labels: ✨ Feature

#21 회원가입 UI작업
  src/main/java/com/kcc/vacation/controller/HelloController.java
  src/main/webapp/WEB-INF/views/auth/signIn.jsp
  src/main/webapp/WEB-INF/views/auth/signup.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/resources/assets/google.PNG
  src/main/webapp/resources/assets/kakaotalk.png
  src/main/webapp/resources/assets/naver.png
  src/main/webapp/resources/css/signup.css
Labels: ✨ Feature

#23 로그인 페이지, 초대인증 모달 UI구현
  src/main/java/com/kcc/vacation/controller/HelloController.java
  src/main/webapp/WEB-INF/views/auth/login.jsp
  src/main/webapp/WEB-INF/views/auth/signup.jsp
  src/main/webapp/resources/css/signup.css
Labels: ✨ Feature

#25 조직관리 UI구현
  src/main/java/com/kcc/vacation/controller/HelloController.java
  src/main/webapp/WEB-INF/views/admin/organizational-management.jsp
  src/main/webapp/WEB-INF/views/auth/signup.jsp
  src/main/webapp/resources/css/organization-management.css
Labels: ✨ Feature
